import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Next.Js Love You",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
          <Header></Header>
          <div className="min-h-screen mx-auto">{children}</div>
          <Footer></Footer>

      </body>
    </html>
  );
}
